apiVersion: v1
kind: PersistentVolume # Resource untuk mendefinisikan penyimpanan persisten di level cluster
metadata:
  name: mongo-pv # Nama PersistentVolume
spec:
  capacity:
    storage: 1Gi # Kapasitas penyimpanan yang dialokasikan
  accessModes:
    - ReadWriteOnce # Hanya dapat diakses read-write oleh satu node
  hostPath:
    path: "/data/mongo" # Path di host (node) tempat data disimpan - cocok untuk development, TIDAK untuk production
---
apiVersion: v1
kind: PersistentVolumeClaim # Request untuk penyimpanan persisten dari Pod
metadata:
  name: mongo-pvc # Nama PVC yang akan direferensikan
spec:
  accessModes:
    - ReadWriteOnce # Mode akses yang sama dengan PV
  resources:
    requests:
      storage: 1Gi # Request penyimpanan sebesar 1GB