apiVersion: apps/v1
kind: StatefulSet # StatefulSet untuk aplikasi stateful seperti database yang membutuhkan identitas jaringan & penyimpanan stabil
metadata:
  name: mongodb # Nama StatefulSet
spec:
  serviceName: "" # Nama service yang terkait dengan StatefulSet
  replicas: 1 # Jumlah Pod yang akan dibuat (hanya 1 instance MongoDB)
  minReadySeconds: 10 # Waktu minimum sebelum Pod dianggap siap
  selector:
    matchLabels:
      app: mongodb # Selector untuk Pod yang dikelola StatefulSet
  template:
    metadata:
      labels:
        app: mongodb # Label untuk Pod MongoDB
    spec:
      containers:
      - name: mongodb # Nama container
        image: mongo:5.0 # Image MongoDB yang digunakan
        ports:
          - containerPort: 27017 # Port yang digunakan oleh MongoDB
        volumeMounts:
          - name: mongo-storage # Volume untuk data MongoDB
            mountPath: /data/db # Path di container untuk menyimpan data
          - name: config-volume # Volume untuk konfigurasi MongoDB
            mountPath: /config
          - name: secret-volume # Volume untuk credentials MongoDB
            mountPath: /etc/mongo-credentials
        env: # Environment variables untuk konfigurasi MongoDB
          - name: MONGO_INITDB_ROOT_USERNAME_FILE # Username MongoDB dari secret
            value: /etc/mongo-credentials/MONGO_ROOT_USERNAME # Path ke file yang berisi username
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE # Password MongoDB dari secret
            value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD # Path ke file yang berisi password
      volumes:
        - name: mongo-storage # Definisi volume untuk konfigurasi
          persistentVolumeClaim: # Menggunakan PersistentVolumeClaim untuk penyimpanan
            claimName: mongo-pvc # Nama PersistentVolumeClaim yang digunakan
        - name: config-volume
          configMap:
            name: mongo-config # Menggunakan ConfigMap untuk konfigurasi MongoDB
            items:
              - key: mongo.conf # Kunci dalam ConfigMap yang akan di-mount
                path: mongo.conf # Nama file di dalam container
        - name: secret-volume # Definisi volume untuk credential
          secret:
            secretName: mongodb-secret # Menggunakan Secret untuk kredensial
  