apiVersion: v1
kind: Secret # Resource Kubernetes untuk menyimpan informasi sensitif (passwords, tokens, keys)
metadata:
  name: mongodb-secret # Nama secret yang akan direferensikan oleh pod
type: Opaque # Tipe secret yang umum digunakan untuk menyimpan data sensitif
data: 
  MONGO_ROOT_USERNAME: YWRtaW4= # encrypted Username untuk MongoDB - dalam produksi seharusnya lebih aman
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # encrypted Password untuk MongoDB - dalam produksi seharusnya lebih aman