apiVersion: v1
kind: Secret # Resource Kubernetes untuk menyimpan informasi sensitif (passwords, tokens, keys)
metadata:
  name: mongodb-secret # Nama secret yang akan direferensikan oleh pod
stringData: # Data disimpan dalam format string (tidak dienkripsi base64 seperti data biasa)
  MONGO_ROOT_USERNAME: admin # Username untuk MongoDB
  MONGO_ROOT_PASSWORD: supersecretpassword # Password untuk MongoDB - dalam produksi seharusnya lebih aman