apiVersion: v1
kind: Service # Resource untuk mengekspos aplikasi backend ke jaringan
metadata:
  name: karsajobs-service # Nama service yang akan digunakan sebagai DNS di dalam cluster
spec:
  type: NodePort # Tipe service yang mengekspos port pada setiap node di cluster
  selector:
    app: karsajobs # Service akan mengarahkan traffic ke Pod dengan label app=karsajobs
  ports:
    - port: 8080 # Port yang diekspos oleh service di dalam cluster
      targetPort: 8080 # Port pada Pod target
      nodePort: 30002 # Port yang diekspos pada semua node cluster (dapat diakses dari luar)