apiVersion: v1
kind: Service # Resource untuk mengekspos aplikasi UI frontend ke jaringan luar
metadata:
  name: karsajobs-ui-service # Nama service UI
spec:
  type: NodePort # Tipe service yang mengekspos port pada setiap node di cluster
  selector:
    app: karsajobs-ui # Service akan mengarahkan traffic ke Pod dengan label app=karsajobs-ui
  ports:
    - port: 80 # Port yang diekspos oleh service di dalam cluster
      targetPort: 8000 # Port pada Pod target
      nodePort: 30001 # Port yang diekspos pada semua node cluster (untuk akses dari browser)