apiVersion: v1
kind: Namespace # Mendefinisikan namespace untuk aplikasi KarsaJobs
metadata:
  name: karsajobs-ns # Nama namespace khusus untuk aplikasi
  labels:
    app: karsajobs # Label untuk mengidentifikasi namespace
